### ISSUE TITLE
tags 

### ISSUE THREAD

**Issue by GiorgioSpring** [Befox/adrodt#2]
Hi, 

1) I download the zip file
2) I decompressedet it in htdocs as following:

   dolibarr/htdocs/adrodt-master/core/modules/modAdrOdt.class.php
   dolibarr/htdocs/adrodt-master/core/substitutions/functions_adrodt.lib.php

3) I Enable AdrOdt module in Interfaces Modules list.

4) I add the some tags in a odt template located in dolibarr/documents/doctemplates/shipment

```
{adrodt_ship_name}
{adrodt_ship_email}
```

5) But the tags not changed in data on the template

I check the all the step but all seems corretct.
Any suggestions what I do wrong?

Thank you and best regards. 
Giorgio

**Comment by brouillon** [comment]
Hi GiorgioSpring, 

The important part of documentation was :

```
Warning, tags must be rounded with {} or [] for arrays (see later) and must be typed with no stop using Office suite (with no backward and no copy-paste). If not doing that, Office suite add some invisible informations making replacement not possible. 
```

Try to remove your tag and add it again in your template,  no stop while typing :-)

**Comment by GiorgioSpring** [comment]
Hi, 
thank you  for your quick reply,
I had already read this reply in the 1 issue so I had checked several times the correct typing of the tags. Please note that the  common tags  as {mycompany_name} work without problem.

Any suggestions what I do wrong? Perhaps I should place the file  functions_adrodt.lib.php in another carpet instead of dolibarr/htdocs/adrodt-master/core/substitutions/

Thank you and best regards
Giorgio

**Comment by brouillon** [comment]
Perhaps, yes, the path must be `dolibarr/htdocs/adrodt/` instead of `dolibarr/htdocs/adrodt-master/`.

**Comment by GiorgioSpring** [comment]
Hi, 
First I rename the path but I incoming in error when I generate the odt. 
Then I decided to  delete and install again the module under the correct path   dolibarr/htdocs/adrodt/ 
step by step as your instruction and as I write in my first message. 

I create a test template  with only 2 tags {ardodt_ship_name} {ardodt_ship_lastname} but  when I try to generate it  I receive  the same error :..... Message: ErrorBadValueForParamNotAString. (complete error message posted and end).
Please note that the previous odt template (without ardodt tags) that i created not longer work : Error HTTP 500.
When I disable the adrodt module the previus odt templates working again.

Thanks for your help and best regards
Giorgio

**Comment by GiorgioSpring** [comment]
This is the complete error message with the odt template created with only the 2 ardodt tags: 
Dolibarr has detected a technical error.
 This is information that can help diagnostic:
Date: 20150911153449
Dolibarr: 3.7.1
Level of features: 0
PHP: 5.5.9-1ubuntu4.9
Server: Apache/2.4.7 (Ubuntu)
OS: Linux ubuntu-12 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:33:09 UTC 2015 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

Requested Url: /htdocs/expedition/card.php?id=13
Referer: http://192.168.0.54/htdocs/expedition/card.php?id=13
Menu manager: eldy_menu.php

Database type manager: mysqli
Request for last database access in error: SELECT subprice as pu_ht, qty, remise_percent, total_ht FROM llx_expeditiondet WHERE fk_expedition = 13
Return code for last database access in error: DB_ERROR_NOSUCHFIELD
Information for last database access in error: Unknown column 'subprice' in 'field list'

Message: Error generating document for CommonObject. Error: 'lines' segment not found in the document
 Dolibarr has detected a technical error.
 This is information that can help diagnostic:
Date: 20150911153449
Dolibarr: 3.7.1
Level of features: 0
PHP: 5.5.9-1ubuntu4.9
Server: Apache/2.4.7 (Ubuntu)
OS: Linux ubuntu-12 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:33:09 UTC 2015 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

Requested Url: /htdocs/expedition/card.php?id=13
Referer: http://192.168.0.54/htdocs/expedition/card.php?id=13
Menu manager: eldy_menu.php

Database type manager: mysqli
Request for last database access in error: SELECT subprice as pu_ht, qty, remise_percent, total_ht FROM llx_expeditiondet WHERE fk_expedition = 13
Return code for last database access in error: DB_ERROR_NOSUCHFIELD
Information for last database access in error: Unknown column 'subprice' in 'field list'

Message: ErrorBadValueForParamNotAString
Giorgio

**Comment by brouillon** [comment]
In your message, i see :

```
Message: Error generating document for CommonObject. Error: 'lines' segment not found in the document
```

It seems the segments `[!-- BEGIN row.lines --]` and `[!-- END row.lines --]` is mandatory. 
Try to add these in your template.

For the error 500, you have to explore server errors (apache and php).

**Comment by GiorgioSpring** [comment]
Hi,
 I have create 2 odt template: 
1) First template  with following line: 
{ardodt_ship_name}
{ardodt_ship_lastname}
2) Second template with following line:
[!-- BEGIN row.lines --]
{ardodt_ship_name}
{ardodt_ship_lastname}
[!-- END row.lines --]

Both not work and generate the same error as before. (see below)
Considers that all the previus default odt not longer work when the ardodt module is active.
(when I deactivite the ardodt module the  previus created odt template working again.)

Thanks for your help and best regards
 Giorgio

**Comment by GiorgioSpring** [comment]
Dolibarr has detected a technical error.
 This is information that can help diagnostic:
Date: 20150911173138
Dolibarr: 3.7.1
Level of features: 0
PHP: 5.5.9-1ubuntu4.9
Server: Apache/2.4.7 (Ubuntu)
OS: Linux ubuntu-12 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:33:09 UTC 2015 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

Requested Url: /htdocs/expedition/card.php?id=13
Referer: http://192.168.0.54/htdocs/expedition/card.php?id=13
Menu manager: eldy_menu.php

Database type manager: mysqli
Request for last database access in error: SELECT subprice as pu_ht, qty, remise_percent, total_ht FROM llx_expeditiondet WHERE fk_expedition = 13
Return code for last database access in error: DB_ERROR_NOSUCHFIELD
Information for last database access in error: Unknown column 'subprice' in 'field list'

Message: Error generating document for CommonObject. Error: 'lines' segment not found in the document
 Dolibarr has detected a technical error.
 This is information that can help diagnostic:
Date: 20150911173138
Dolibarr: 3.7.1
Level of features: 0
PHP: 5.5.9-1ubuntu4.9
Server: Apache/2.4.7 (Ubuntu)
OS: Linux ubuntu-12 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:33:09 UTC 2015 i686
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

Requested Url: /htdocs/expedition/card.php?id=13
Referer: http://192.168.0.54/htdocs/expedition/card.php?id=13
Menu manager: eldy_menu.php

Database type manager: mysqli
Request for last database access in error: SELECT subprice as pu_ht, qty, remise_percent, total_ht FROM llx_expeditiondet WHERE fk_expedition = 13
Return code for last database access in error: DB_ERROR_NOSUCHFIELD
Information for last database access in error: Unknown column 'subprice' in 'field list'

Message: ErrorBadValueForParamNotAString

**Comment by yehanny** [comment]
Hi @GiorgioSpring It seems your having same problem I had. The first thing you can do it's to place the tags in separates cells into a table. [!-- BEGIN row.lines --] goes in the first cell before the tag {ardodt_ship_lastname} then next cell {ardodt_ship_name}[!-- END row.lines --] end of cell.

You can try also cut the code and paste in Notepad to clear the format, then cut and paste again inside .ODT document, save, close, upload and try again to generate the document inside dolibarr (remember to close the document before upload) then post results. This method worked for me... :)  :+1:

**Comment by GiorgioSpring** [comment]
Hi and thank you for your tip, 
I follow exactly your instructions I crete in a clear format a new odt:
[!-- BEGIN row.lines --] {ardodt_ship_lastname}
{ardodt_ship_name} [!-- END row.lines --] 
but  I receive the same error as before.

The odd thing is that when the ardodt module is active all the previus template no more work.

Thanks for your help and best regards
 Giorgio

**Comment by brouillon** [comment]
New version for debug :) 
You can update adrodt version and test with this odt template :
https://github.com/Befox/adrodt/blob/master/adrodt_invoice.odt

For other template don't work when the module is active please check your server error (apache or php)
