### ISSUE TITLE
Shippingcontact works in invoice but not in shipment

### ISSUE THREAD

**Issue by KingKone** [Befox/adrodt#5]
Hello! 
Your module is very usefull... should do exactly what I need but something is not working correctly:

I've installed the module in the root path and activaed it. 
When I add a shipping contact in the invoice module the new extra fields are getting filled with the shipping contact when genarating the odt there, but when I try the same in the shipping module the normal partner address is filled in. 

Do you have any sugestion, what is going wrong?
Is there maybe an other place where I have to tell the system that 'this' ist the shipping address?

I'm using Dolibarr 3.9.2

**From invoice:**
adrodt_debug_lines = Substitution Array: 
Array
(
 [line_fulldesc] => 04753062 - RFPA E6 DORA
For Harmony systems refer tocomment of partnumber 10432637(cable W309)
 [line_product_ref] => 04753062
 [line_product_label] => RFPA E6 DORA
 [line_product_type] => 0
 [line_desc] => For Harmony systems refer tocomment of partnumber 10432637(cable W309)
 [line_vatrate] => 19%
 [line_up] => 8000
 [line_up_locale] => 8.000,00
 [line_qty] => 1
 [line_discount_percent] => 
 [line_price_ht] => 8000
 [line_price_ttc] => 9520
 [line_price_vat] => 1520
 [line_price_ht_locale] => 8.000,00
 [line_price_ttc_locale] => 9.520,00
 [line_price_vat_locale] => 1.520,00
 [line_date_start] => 
 [line_date_start_rfc] => 
 [line_date_end] => 
 [line_date_end_rfc] => 
)

**From Shippment:**
adrodt_debug_lines = Substitution Array: 
Array
(
 [line_fulldesc] => 04753062 - RFPA E6 DORA
For Harmony systems refer tocomment of partnumber 10432637(cable W309)
 [line_product_ref] => 04753062
 [line_product_label] => RFPA E6 DORA
 [line_desc] => For Harmony systems refer tocomment of partnumber 10432637(cable W309)
 [line_vatrate] => 19%
 [line_up] => 8.000,00
 [line_qty] => 1
 [line_qty_shipped] => 1
 [line_qty_asked] => 1
 [line_discount_percent] => 
 [line_price_ht] => 8.000,00
 [line_price_ttc] => 9.520,00
 [line_price_vat] => 1.520,00
 [line_weight] => 23 
 [line_length] => 
 [line_surface] => 
 [line_volume] => 
)

**Comment by jpfox** [comment]
It is fixed in last version.
In expedition, attached contacts are stored in order, so module search them in origin document now.
