### ISSUE TITLE
Not working with Dolibarr 4.0x

### ISSUE THREAD

**Issue by tvidal-34** [Befox/adrodt#6]
Dear,

Just to let you know that this useful addon is not working with Dolibarr 4.0x (I'd tried your odt debug file)

Did you plan to update your addon ?

All the best

Thomas

**Comment by jpfox** [comment]
We have not tried it on 4.0 yet. It will depends on problem encountered. We don't know how odt generation has evolved in this version.
We will notify you in this issue to let you know

**Comment by tvidal-34** [comment]
Many thanks Jean-Pierre.
All the best

**Comment by AlbioB** [comment]
Hello, any news on 4.x - 5.x support?
Thanks

**Comment by agnux7** [comment]
Hello, any news on 6.x - 7.x support?
Thanks

**Comment by jpfox** [comment]
adrodt supports Dolibarr 8.0 since last commit
